DROP DATABASE IF EXISTS `bluebonnet`;
DROP DATABASE IF EXISTS `demo`;
DROP DATABASE IF EXISTS `frontier`;
DROP DATABASE IF EXISTS `immixcms`;
DROP DATABASE IF EXISTS `immixpro`;
DROP DATABASE IF EXISTS `jgcamerica`;
DROP DATABASE IF EXISTS `newhomewalk`;

CREATE DATABASE IF NOT EXISTS `bluebonnet`;
CREATE DATABASE IF NOT EXISTS `demo`;
CREATE DATABASE IF NOT EXISTS `frontier`;
CREATE DATABASE IF NOT EXISTS `immixcms`;
CREATE DATABASE IF NOT EXISTS `immixpro`;
CREATE DATABASE IF NOT EXISTS `jgcamerica`;
CREATE DATABASE IF NOT EXISTS `newhomewalk`;
